### ISSUE TITLE
function to download only specific companies data

### ISSUE THREAD

**Issue by cobap** [SimFin/simfin-tutorials#13]
Hello! I would like to know if there is a way to only download specific company data. I want to time to time review some company financials (about 30 companies). Does not make sense to download the entire dataset just for data

Thanks in advance.,

**Comment by thf24** [comment]
If you want to download data for specific companies I would suggest using the web API, which has a similar output format to the bulk data: https://simfin.com/api/v2/documentation/
https://github.com/SimFin/web-api-examples

**Comment by cobap** [comment]
Hey Thomas, I'll take a look on the webAPI, thanks. 

Just a comment, since you encourage people to download the python package, maybe is a nice idea to add on the backlog
