### ISSUE TITLE
Empty repo... or just not rendered ?

### ISSUE THREAD

**Issue by datatalking** [SimFin/simfin-tutorials#17]
I was trying to view the .ipynb files in your https://github.com/SimFin/simfin-tutorials/blob/master/01_Basics.ipynb repo but they are not showing up.

![Screen Shot 2022-11-04 at 3 22 46 PM](https://user-images.githubusercontent.com/11813209/200083566-257f91fb-a52c-4a9e-b775-aac16b64fb90.png)

**Comment by thf24** [comment]
should work if you refresh the page
