### ISSUE TITLE
Divide by zero error chapter 9

### ISSUE THREAD

**Issue by JeremyWhittaker** [SimFin/simfin-tutorials#9]
I'm getting the following error when trying to run this command. 
```

%%time
df_fin_signals = hub.fin_signals(variant='daily')
```

RuntimeWarning: divide by zero encountered in log10
  result = getattr(ufunc, method)(*inputs, **kwargs)
RuntimeWarning: invalid value encountered in log10
  result = getattr(ufunc, method)(*inputs, **kwargs)

**Comment by thf24** [comment]
Hi, this looks like a warning and not an error? If it's a warning you can safely ignore it.
